
const skillOptions = [
  { value: "Agile", label: "Agile" },
  { value: "Angular", label: "Angular" },
  { value: "Ansible", label: "Ansible" },
  { value: "ASP.NET", label: "ASP.NET" },
  { value: "AWS", label: "AWS" },
  { value: "Bash", label: "Bash" },
  { value: "Big Data", label: "Big Data" },
  { value: "Blockchain", label: "Blockchain" },
  { value: "C#", label: "C#" },
  { value: "C++", label: "C++" },
  { value: "CI/CD", label: "CI/CD" },
  { value: "Cloud Computing", label: "Cloud Computing" },
  { value: "CSS", label: "CSS" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "Data Engineering", label: "Data Engineering" },
  { value: "Data Science", label: "Data Science" },
  { value: "Deep Learning", label: "Deep Learning" },
  { value: "DevOps", label: "DevOps" },
  { value: "Django", label: "Django" },
  { value: "Docker", label: "Docker" },
  { value: "Express.js", label: "Express.js" },
  { value: "Flask", label: "Flask" },
  { value: "Git", label: "Git" },
  { value: "GitHub", label: "GitHub" },
  { value: "GitLab", label: "GitLab" },
  { value: "Go", label: "Go" },
  { value: "Google Cloud", label: "Google Cloud" },
  { value: "GraphQL", label: "GraphQL" },
  { value: "Hadoop", label: "Hadoop" },
  { value: "HTML", label: "HTML" },
  { value: "Java", label: "Java" },
  { value: "JavaScript", label: "JavaScript" },
  { value: "Jenkins", label: "Jenkins" },
  { value: "JIRA", label: "JIRA" },
  { value: "Keras", label: "Keras" },
  { value: "Kotlin", label: "Kotlin" },
  { value: "Kubernetes", label: "Kubernetes" },
  { value: "Laravel", label: "Laravel" },
  { value: "Linux", label: "Linux" },
  { value: "Machine Learning", label: "Machine Learning" },
  { value: "MongoDB", label: "MongoDB" },
  { value: "MySQL", label: "MySQL" },
  { value: "Networking", label: "Networking" },
  { value: "Next.js", label: "Next.js" },
  { value: "NLP", label: "NLP" },
  { value: "Node.js", label: "Node.js" },
  { value: "NoSQL", label: "NoSQL" },
  { value: "Penetration Testing", label: "Penetration Testing" },
  { value: "PHP", label: "PHP" },
  { value: "PostgreSQL", label: "PostgreSQL" },
  { value: "Power BI", label: "Power BI" },
  { value: "Powershell", label: "Powershell" },
  { value: "PyTorch", label: "PyTorch" },
  { value: "Python", label: "Python" },
  { value: "React", label: "React" },
  { value: "RESTful APIs", label: "RESTful APIs" },
  { value: "Ruby", label: "Ruby" },
  { value: "Ruby on Rails", label: "Ruby on Rails" },
  { value: "Sass", label: "Sass" },
  { value: "Scrum", label: "Scrum" },
  { value: "Spark", label: "Spark" },
  { value: "Spring Boot", label: "Spring Boot" },
  { value: "SQL", label: "SQL" },
  { value: "SQLite", label: "SQLite" },
  { value: "Swift", label: "Swift" },
  { value: "Tableau", label: "Tableau" },
  { value: "TensorFlow", label: "TensorFlow" },
  { value: "Terraform", label: "Terraform" },
  { value: "TypeScript", label: "TypeScript" },
  { value: "Vue.js", label: "Vue.js" },
  { value: "Virtualization", label: "Virtualization" }
];
export default skillOptions;